### ISSUE TITLE
consider changing executable name

### ISSUE THREAD

**Issue by wayofthefuture** [pirelenito/git-x#6]
might want to consider changing the executable name. I get a really eerie feeling by this overriding the git executable. I think git-x or gitx would be a more appropriate name. Not having a complete understanding of how the override works, no longer using as don't want unexpected / weird behavior with git. Thanks.

**Comment by pirelenito** [comment]
Thanks for the issue!

But, I'm not overwriting `git`, I'm simply adding a new command by adhering to one of its conventions.

The actual executable name is indeed `git-x`, as you can see from [Installation documentation](https://github.com/pirelenito/git-x#instalation). 

You are still using the original `git` executable. But what `git` does is that if you try to use a command that it doesn't understand, it will try to find it then in the `PATH`. This is the "magic" that makes this work as `git x`.

This practice is also [fairly used in the community](http://thediscoblog.com/blog/2014/03/29/custom-git-commands-in-3-steps/).

I'm closing this ticket, hope I have answered your question.

**Comment by wayofthefuture** [comment]
Yup, I stand corrected. Reinstalling now! Thanks!
